name: PluginEchec
version: 1.0
main: me.pepelucifer.echecs.Echecs
api-version: 1.16
authors: [ pepelucifer, clement_du_57 ]
description: Un plugin qui permet de jouer aux échecs sur Minecraft.
commands:
  chess:
    description: Rejoindre un salon d'échecs
    usage: /<command>
    aliases: c
  quit:
    description: Quitter un salon d'échecs
    usage: /<command>
    aliases: q