name: Echecs
version: 1.0
main: me.pepelucifer.echecs.Echecs
api-version: 1.16
authors: [ pepelucifer, clement_du_57 ]
description: Un plugin qui permet de jouer aux échecs sur Minecraft.
softdepend: [Multiverse-Core,ExtraWorlds,AmongUs]


commands:
  echecs:
    description: Rejoindre un salon d'échecs
    usage: /<command>
    aliases: e
  quitter:
    description: Quitter un salon d'échecs
    usage: /<command>
    aliases: q
  dev:
    description: Propriétés spéciales pour développement
    usage: /<command>
    aliases: d
  echecsaccept:
    description: Accepter une requête d'échecs
    usage: /<command> <args>
  echecsnulle:
    description: Accepter ou refuser la nulle
    usage: /<command> <args>